apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pv1-nfs-system
  namespace: kube-system
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/linuxidc
    server: 128.110.153.168
